[package]
name = "parsegcache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoffset = "0.8.0"
sharded-slab = "0.1.4"
thiserror = "1.0.37"
